### ISSUE TITLE
Does not work when using dots as decimal separator

### ISSUE THREAD

**Issue by kr1-ch** [bazh/subtitles-parser#12]
The `fromSrt()` function does not work when dots are used as decimal separator (instead commas).
For example:

```
1
00:00:04.240 --> 00:00:09.570
way.

2
00:00:09.570 --> 00:00:10.860
Love about Eurovision.

3
00:00:11.080 --> 00:00:16.050
The whole world's participating on to make sure the world remains a great place that

4
00:00:16.050 --> 00:00:16.450
it is.

5
00:00:16.640 --> 00:00:19.850
We're hosting this song contest as a green events,
```

Apparently it works well with both commas and dots when changing the regex at line 21:
`var regex = /(\d+)\n(\d{2}:\d{2}:\d{2},\d{3}) --> (\d{2}:\d{2}:\d{2},\d{3})/g;`
to:
`var regex = /(\d+)\n(\d{2}:\d{2}:\d{2}.\d{3}) --> (\d{2}:\d{2}:\d{2}.\d{3})/g;`

**Comment by krownwebsolutions** [comment]
test
