### ISSUE TITLE
async

### ISSUE THREAD

**Issue by Sheraff** [bazh/subtitles-parser#4]
Hi, would you consider approaching this in an async way? Where instead of 

`var data = parser.fromSrt(srt);`

You would do

```js
parser.fromSrt(srt, function(data){
   // some code
});
```

or (with **q**)

```js
parser.fromSrt(srt).then(function(data){
   // some code
});
```

Theoretically, this would allow for faster parsing of multiple subtitle files (i think).

**Comment by bazh** [comment]
Hi @Sheraff

Good suggestion! But implementation of `fromSrt` function doesn't have any async code inside.
I think, If you'd like to parse multiple files in one time you may use async module:
```
async.parallel([function(done) {
   done(null, parser.fromSrt(srt))
}, ...], function(err, res) {
   console.log('yay, we've parsed all data!')
})
```

But I don't think that this will speed up parsing time for multiple files. Async.parallel will just not lock your code

**Comment by Sheraff** [comment]
Yeah I thought about that just after posting... I guess it's just a node reflex :-)
