### ISSUE TITLE
hi bazh 

### ISSUE THREAD

**Issue by pipecivil** [bazh/subtitles-parser#6]
hi thank you your npm

npm install subtitles-parser
this is correct 

but this page incorrect word
npm install subtitles-parser
<img width="998" alt="2015-12-23 8 44 40" src="https://cloud.githubusercontent.com/assets/4828753/11975932/35a8e0d6-a9b6-11e5-8e21-22e617aa2598.png">

**Comment by bazh** [comment]
Hi @pipecivil,

Yeah, it's a known typo which is already fixed in a repo.
Unfortunately, I have no plans to update npm package in near future (Just don't want to bump package version because of typo in a README file). We have to wait for any major change in a module :)
